services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d scheduler_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl_core:
    build: ./app
    container_name: etl_core
    command: python app.py
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@postgres:5432/scheduler_db
      FLASK_ENV: development
      QUESTDB_URL: 192.168.8.123
      QUESTDB_PORT: 9999
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
      - /mnt/ssd/etldownloaded:/app/yfdata
volumes:
  postgres_data:
